services:
  webapp-dev:
    container_name: webapp-shopping-list-dev
    build:
      context: ./webapp
      dockerfile: /docker/dev.Dockerfile

    # Set environment variables directly in the docker-compose file
    environment:
      TEST_VAR: ${TEST_VAR}
      SECRET_VAR: ${SECRET_VAR}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public
      NEXT_PUBLIC_DEFAULT_REGISTER_PASSWORD: ${NEXT_PUBLIC_DEFAULT_REGISTER_PASSWORD}
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_TRUST_HOST: ${AUTH_TRUST_HOST}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      RESEND_API_KEY: ${RESEND_API_KEY}
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
      NEXTAUTH_URL: ${NEXT_PUBLIC_APP_URL}

    # Set environment variables based on the .env file
    # env_file:
    #   - .env
    restart: always
    ports:
      - 3004:3000
    develop:
      watch:
        - action: sync
          path: ./webapp/src
          target: /app/src
          ignore:
            - node_modules/
        - action: sync
          path: ./webapp/tailwind.config.ts
          target: /app/tailwind.config.ts
        - action: rebuild
          path: package.json

  db:
    image: postgres:16-alpine
    container_name: postgres-shopping-list
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Bucharest
    ports:
      - 5434:5432
    volumes:
      - ./db:/var/lib/postgresql/data
